global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # Raspa métricas da aplicação Spring Boot
  - job_name: "kafka"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8083"]
        labels:
          application: "kafka"
          ambiente: "local"

  # Raspa métricas do próprio Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
